// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kertaskerja Dev Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "checking if this service is accessible",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_HealthcheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/individu/rekin": {
            "get": {
                "description": "Mengambil data rencana kinerja individu berdasarkan id_pegawai, kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Individu"
                ],
                "summary": "Get rencana kinerja individu penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id Pegawai",
                        "name": "pegawaiId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data rekin individu",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-web_RekinIndividuResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/individu/rekin/archive": {
            "put": {
                "description": "Arsipkan data pk penetapan berdasarkan id_pegawai, kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Individu"
                ],
                "summary": "Archive Rekin individu",
                "parameters": [
                    {
                        "description": "Payload sync penetapan individu",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/individu/rekin/sync": {
            "post": {
                "description": "Sinkron data pk penetapan berdasarkan id_pegawai, kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Individu"
                ],
                "summary": "Sync Rekin individu",
                "parameters": [
                    {
                        "description": "Payload sync penetapan individu",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-github_com_bappeda-dev-team_penetapan-service_internal_individu_web_SyncPenetapanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/individu/renaksi": {
            "get": {
                "description": "Mengambil data rencana aksi individu berdasarkan id_pegawai, kode OPD, bulan renaksi dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Individu"
                ],
                "summary": "Get rencana kinerja individu penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id Pegawai",
                        "name": "pegawaiId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bulan Renaksi",
                        "name": "bulan",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data rekin individu",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-web_RenaksiPenetapanIndividuResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/individu/renja": {
            "get": {
                "description": "Mengambil data renja individu berdasarkan id_pegawai, kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Individu"
                ],
                "summary": "Get rencana kinerja individu penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id Pegawai",
                        "name": "pegawaiId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data rekin individu",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-web_RenjaIndividuResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/individu/renja/sync": {
            "post": {
                "description": "Sinkron data pk renja individu berdasarkan id_pegawai, kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Individu"
                ],
                "summary": "Sync Renja individu",
                "parameters": [
                    {
                        "description": "Payload sync penetapan individu",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-github_com_bappeda-dev-team_penetapan-service_internal_individu_web_SyncPenetapanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/renaksi": {
            "get": {
                "description": "Mengambil data renaksi OPD berdasarkan kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Get renaksi OPD penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data renja OPD",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_RenaksiOpdPenetapanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/renja": {
            "get": {
                "description": "Mengambil data renja OPD berdasarkan kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Get renja OPD penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data renja OPD",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_RenjaPenetapanOpdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/renja/sync": {
            "post": {
                "description": "Sinkron data penetapan renja OPD berdasarkan kode OPD dan tahun dari perencanaan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Sync Penetapan Renja OPD",
                "parameters": [
                    {
                        "description": "Payload sinkronisasi penetapan OPD",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SyncPenetapanOpdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_SyncPenetapanOpdResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/sasaran": {
            "get": {
                "description": "Mengambil data sasaran OPD berdasarkan kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Get sasaran OPD penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data sasaran OPD",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_SasaranPenetapanOpdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/sasaran/sync": {
            "post": {
                "description": "Sinkron data penetapan sasaran OPD berdasarkan kode OPD dan tahun dari perencanaan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Sync Penetapan Sasaran OPD",
                "parameters": [
                    {
                        "description": "Payload sinkronisasi penetapan OPD",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SyncPenetapanOpdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_SyncPenetapanOpdResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/tujuan": {
            "get": {
                "description": "Mengambil data tujuan OPD berdasarkan kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Get tujuan OPD penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data tujuan OPD",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_TujuanPenetapanOpdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/tujuan-with-sasaran": {
            "get": {
                "description": "Mengambil data tujuan dan sasaran OPD berdasarkan kode OPD dan tahun penetapan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Get tujuan sasaran OPD penetapan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kodeOpd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data tujuan OPD",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_TujuanSasaranPenetapanOpdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/opd/tujuan/sync": {
            "post": {
                "description": "Sinkron data penetapan tujuan OPD berdasarkan kode OPD dan tahun dari perencanaan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OPD"
                ],
                "summary": "Sync Penetapan Tujuan OPD",
                "parameters": [
                    {
                        "description": "Payload sinkronisasi penetapan OPD",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SyncPenetapanOpdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_SyncPenetapanOpdResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pemda/sasaran": {
            "get": {
                "description": "Mengambil snapshot sasaran Pemda aktif berdasarkan tahun",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pemda"
                ],
                "summary": "Get sasaran Pemda penetapan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-web_SasaranPenetapanPemdaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pemda/sasaran/sync": {
            "post": {
                "description": "Sinkron data sasaran Pemda berdasarkan tahun",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pemda"
                ],
                "summary": "Sync sasaran Pemda",
                "parameters": [
                    {
                        "description": "Payload sync penetapan Pemda",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.SyncPenetapanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-github_com_bappeda-dev-team_penetapan-service_internal_pemda_web_SyncPenetapanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pemda/tujuan": {
            "get": {
                "description": "Mengambil snapshot tujuan Pemda aktif berdasarkan tahun",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pemda"
                ],
                "summary": "Get tujuan Pemda penetapan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-web_TujuanPenetapanPemdaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pemda/tujuan-with-sasaran": {
            "get": {
                "description": "Mengambil snapshot tujuan dan sasaran Pemda aktif berdasarkan tahun",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pemda"
                ],
                "summary": "Get tujuan with sasaran Pemda penetapan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tahun Penetapan",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-web_TujuanSasaranPenetapanPemdaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pemda/tujuan/sync": {
            "post": {
                "description": "Sinkron data tujuan pemda berdasarkan tahun",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pemda"
                ],
                "summary": "Sync Tujuan pemda",
                "parameters": [
                    {
                        "description": "Payload sync penetapan pemda",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.SyncPenetapanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-github_com_bappeda-dev-team_penetapan-service_internal_pemda_web_SyncPenetapanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_domain.JenisPenetapan": {
            "type": "string",
            "enum": [
                "PK-INDIVIDU",
                "RENJA-INDIVIDU"
            ],
            "x-enum-varnames": [
                "JenisPenetapanPk",
                "JenisPenetapanRenjaIndividu"
            ]
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-github_com_bappeda-dev-team_penetapan-service_internal_individu_web_SyncPenetapanResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-web_RekinIndividuResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.RekinIndividuResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-web_RenaksiPenetapanIndividuResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.RenaksiPenetapanIndividuResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.Response-web_RenjaIndividuResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.RenjaIndividuResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanRequest": {
            "type": "object",
            "properties": {
                "bulan": {
                    "type": "integer",
                    "example": 5
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.22.33"
                },
                "pegawai_id": {
                    "type": "string",
                    "example": "199887766"
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanResponse": {
            "type": "object",
            "properties": {
                "jenis_penetapan": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_domain.JenisPenetapan"
                        }
                    ],
                    "example": "REKIN"
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.22.33"
                },
                "pegawai_id": {
                    "type": "string",
                    "example": "1998877665544"
                },
                "processed_at": {
                    "type": "string"
                },
                "processed_summary": {
                    "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanSummary"
                },
                "status": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "sync_id": {
                    "type": "integer",
                    "example": 155
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.SyncPenetapanSummary": {
            "type": "object",
            "properties": {
                "indikator": {
                    "type": "integer",
                    "example": 3
                },
                "indikator_renja_individu": {
                    "type": "integer",
                    "example": 6
                },
                "renaksi": {
                    "type": "integer",
                    "example": 3
                },
                "rencana_kinerja": {
                    "type": "integer",
                    "example": 1
                },
                "renja_individu": {
                    "type": "integer",
                    "example": 6
                },
                "target": {
                    "type": "integer",
                    "example": 4
                },
                "target_renja_individu": {
                    "type": "integer",
                    "example": 6
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_individu_web.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "kode_opd": "required",
                        "pegawai_id": "required",
                        "tahun": "required"
                    }
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_HealthcheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.HealthcheckResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_RenaksiOpdPenetapanResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.RenaksiOpdPenetapanResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_RenjaPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.RenjaPenetapanOpdResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_SasaranPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.SasaranPenetapanOpdResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_SyncPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.SyncPenetapanOpdResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_TujuanPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.TujuanPenetapanOpdResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.Response-web_TujuanSasaranPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.TujuanSasaranPenetapanOpdResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_model_web.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "kode_opd": "required",
                        "tahun": "required"
                    }
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_domain.JenisPenetapan": {
            "type": "string",
            "enum": [
                "TUJUAN-PEMDA",
                "SASARAN-PEMDA"
            ],
            "x-enum-varnames": [
                "JenisPenetapanTujuanPemda",
                "JenisPenetapanSasaranPemda"
            ]
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-github_com_bappeda-dev-team_penetapan-service_internal_pemda_web_SyncPenetapanResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.SyncPenetapanResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-web_SasaranPenetapanPemdaResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.SasaranPenetapanPemdaResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-web_TujuanPenetapanPemdaResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.TujuanPenetapanPemdaResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.Response-web_TujuanSasaranPenetapanPemdaResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.TujuanSasaranPenetapanPemdaResponse"
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.SyncPenetapanRequest": {
            "type": "object",
            "properties": {
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.SyncPenetapanResponse": {
            "type": "object",
            "properties": {
                "jenis_penetapan": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_domain.JenisPenetapan"
                        }
                    ],
                    "example": "TUJUAN-PEMDA"
                },
                "processed_at": {
                    "type": "string"
                },
                "processed_summary": {
                    "$ref": "#/definitions/github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.SyncPenetapanSummary"
                },
                "status": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "sync_id": {
                    "type": "integer",
                    "example": 155
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.SyncPenetapanSummary": {
            "type": "object",
            "properties": {
                "indikator": {
                    "type": "integer",
                    "example": 3
                },
                "sasaran_pemda": {
                    "type": "integer",
                    "example": 1
                },
                "target": {
                    "type": "integer",
                    "example": 4
                },
                "tujuan_pemda": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "github_com_bappeda-dev-team_penetapan-service_internal_pemda_web.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "tahun": "required"
                    }
                }
            }
        },
        "web.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "system_info": {
                    "$ref": "#/definitions/web.HealthcheckSystemInfo"
                }
            }
        },
        "web.HealthcheckSystemInfo": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "web.IndikatorPemdaPenetapanResponse": {
            "type": "object",
            "properties": {
                "definisi_operasional": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "string"
                },
                "kode_indikator": {
                    "type": "string"
                },
                "rumus_perhitungan": {
                    "type": "string"
                },
                "sumber_data": {
                    "type": "string"
                },
                "tahun_aktif": {
                    "type": "integer"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetPemdaResponse"
                    }
                }
            }
        },
        "web.IndikatorPkResponse": {
            "type": "object",
            "properties": {
                "definisi_operasional": {
                    "type": "string",
                    "example": "Persentase responden yang menyatakan puas"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "kode_indikator_pk": {
                    "type": "string",
                    "example": "IKU-001"
                },
                "kode_indikator_sasaran_opd": {
                    "type": "string",
                    "example": "IND-1"
                },
                "nama_indikator_pk": {
                    "type": "string",
                    "example": "Persentase kepuasan masyarakat"
                },
                "rumus_perhitungan": {
                    "type": "string",
                    "example": "Jumlah puas / total responden x 100%"
                },
                "sumber_data": {
                    "type": "string",
                    "example": "Survei Kepuasan Masyarakat"
                },
                "target_pk": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetPkResponse"
                    }
                }
            }
        },
        "web.IndikatorRenja": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikator": {
                    "type": "string",
                    "example": "INDIKATOR-PROGRAM-1"
                },
                "kode_indikator": {
                    "type": "string",
                    "example": "IND-RENJA-123"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetRenja"
                    }
                }
            }
        },
        "web.IndikatorRenjaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "string",
                    "example": "TEST-INDIKATOR"
                },
                "kode_indikator": {
                    "type": "string",
                    "example": "IND-123"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetIndikatorResponse"
                    }
                }
            }
        },
        "web.IndikatorSasaranPenetapanResponse": {
            "type": "object",
            "properties": {
                "definisi_operasional": {
                    "type": "string",
                    "example": "definisi abc"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikator": {
                    "type": "string",
                    "example": "Indikator kepuasa publik"
                },
                "kode_indikator": {
                    "type": "string",
                    "example": "IND-TUJ-01"
                },
                "rumus_perhitungan": {
                    "type": "string",
                    "example": "indeks kepuasan masyarakat"
                },
                "sumber_data": {
                    "type": "string",
                    "example": "bps"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetIndikatorResponse"
                    }
                }
            }
        },
        "web.IndikatorTujuanPenetapanResponse": {
            "type": "object",
            "properties": {
                "definisi_operasional": {
                    "type": "string",
                    "example": "definisi abc"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikator": {
                    "type": "string",
                    "example": "Indikator kepuasa publik"
                },
                "kode_indikator": {
                    "type": "string",
                    "example": "IND-TUJ-01"
                },
                "rumus_perhitungan": {
                    "type": "string",
                    "example": "indeks kepuasan masyarakat"
                },
                "sumber_data": {
                    "type": "string",
                    "example": "bps"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TargetIndikatorResponse"
                    }
                }
            }
        },
        "web.PaguAnggaranRenjaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jenis_pagu": {
                    "type": "string",
                    "example": "PENETAPAN"
                },
                "kode_pagu": {
                    "type": "string",
                    "example": "PAGU-UR-123"
                },
                "pagu": {
                    "type": "integer",
                    "example": 100000
                }
            }
        },
        "web.PelaksanaanRenaksiPkResponse": {
            "type": "object",
            "properties": {
                "bobot_pelaksanaan": {
                    "type": "integer",
                    "example": 10
                },
                "bulan_pelaksanaan": {
                    "type": "integer",
                    "example": 12
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "kode_pelaksanaan": {
                    "type": "string",
                    "example": "PEL-001"
                }
            }
        },
        "web.RekinIndividuResponse": {
            "type": "object",
            "properties": {
                "anggaran_pk": {
                    "type": "integer",
                    "example": 500000
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikator_pk": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorPkResponse"
                    }
                },
                "keterangan_pk": {
                    "type": "string",
                    "example": "Kinerja utama individu"
                },
                "kode_pk": {
                    "type": "string",
                    "example": "RK-001"
                },
                "kode_sasaran_opd": {
                    "type": "string",
                    "example": "SAS-OPD-1"
                },
                "level_pk": {
                    "type": "integer",
                    "example": 2
                },
                "nama_pemilik_pk": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "rekin": {
                    "type": "string",
                    "example": "Terwujudnya pelayanan publik yang berkualitas"
                },
                "renaksis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenaksiPkResponse"
                    }
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.RenaksiOpdPenetapanResponse": {
            "type": "object",
            "properties": {
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.02.0.00.0.00.01.0000"
                },
                "renaksiOpds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenaksiOpdResponse"
                    }
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.RenaksiOpdResponse": {
            "type": "object",
            "properties": {
                "renaksi": {
                    "type": "string",
                    "example": "terwujudnya xx"
                }
            }
        },
        "web.RenaksiPenetapanIndividuResponse": {
            "type": "object",
            "properties": {
                "bulan": {
                    "type": "integer",
                    "example": 10
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.23.456"
                },
                "nama": {
                    "type": "string",
                    "example": "Pegawai X"
                },
                "pegawai_id": {
                    "type": "string",
                    "example": "12345"
                },
                "rekins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RekinIndividuResponse"
                    }
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "web.RenaksiPkResponse": {
            "type": "object",
            "properties": {
                "anggaran_renaksi": {
                    "type": "integer",
                    "example": 100000
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "kode_renaksi": {
                    "type": "string",
                    "example": "REN-001"
                },
                "nama_renaksi": {
                    "type": "string",
                    "example": "Rapat Koordinasi"
                },
                "pelaksanaans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PelaksanaanRenaksiPkResponse"
                    }
                },
                "urutan_renaksi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.RenjaBidangUrusanResponse": {
            "type": "object",
            "properties": {
                "bidang_urusan": {
                    "type": "string",
                    "example": "URUSAN PEMERINTAHAN BIDANG PENDIDIKAN"
                },
                "id": {
                    "type": "integer"
                },
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_bidang_urusan": {
                    "type": "string",
                    "example": "1.01"
                },
                "pagu_anggaran": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PaguAnggaranRenjaResponse"
                    }
                }
            }
        },
        "web.RenjaIndividu": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikator_kegiatans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorRenja"
                    }
                },
                "indikator_programs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorRenja"
                    }
                },
                "indikator_subkegiatans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorRenja"
                    }
                },
                "kode_kegiatan": {
                    "type": "string",
                    "example": "8.01.05.2.01"
                },
                "kode_pagu_kegiatan": {
                    "type": "string",
                    "example": "PAGU-KEG-xxxx"
                },
                "kode_pagu_program": {
                    "type": "string",
                    "example": "PAGU-PRG-xxxx"
                },
                "kode_pagu_subkegiatan": {
                    "type": "string",
                    "example": "PAGU-SUBKEG-xxxx"
                },
                "kode_pk": {
                    "type": "string",
                    "example": "RK-001"
                },
                "kode_program": {
                    "type": "string",
                    "example": "8.01.05"
                },
                "kode_subkegiatan": {
                    "type": "string",
                    "example": "8.01.05.2.01.0003"
                },
                "level_pk": {
                    "type": "integer",
                    "example": 5
                },
                "nama_kegiatan": {
                    "type": "string",
                    "example": "KEGIATAN XX"
                },
                "nama_pegawai": {
                    "type": "string",
                    "example": "Pegawai X"
                },
                "nama_program": {
                    "type": "string",
                    "example": "PROGRAM ABC"
                },
                "nama_subkegiatan": {
                    "type": "string",
                    "example": "SUBKEGIATAN X"
                },
                "pagu_kegiatan": {
                    "type": "integer",
                    "example": 1250000000
                },
                "pagu_program": {
                    "type": "integer",
                    "example": 2500000000
                },
                "pagu_subkegiatan": {
                    "type": "integer",
                    "example": 500000000
                },
                "pegawai_id": {
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "web.RenjaIndividuResponse": {
            "type": "object",
            "properties": {
                "kode_opd": {
                    "type": "string",
                    "example": "1.23.456"
                },
                "nama": {
                    "type": "string",
                    "example": "Pegawai X"
                },
                "pegawai_id": {
                    "type": "string",
                    "example": "12345777"
                },
                "renjas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenjaIndividu"
                    }
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "web.RenjaKegiatanResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorRenjaResponse"
                    }
                },
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kegiatan": {
                    "type": "string",
                    "example": "KEGIATAN X"
                },
                "kode_kegiatan": {
                    "type": "string",
                    "example": "1.01.01.01.01.01"
                },
                "pagu_anggaran": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PaguAnggaranRenjaResponse"
                    }
                }
            }
        },
        "web.RenjaPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "bidang_urusans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenjaBidangUrusanResponse"
                    }
                },
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kegiatans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenjaKegiatanResponse"
                    }
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.02.0.00.0.00.01.0000"
                },
                "programs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenjaProgramResponse"
                    }
                },
                "subkegiatans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenjaSubkegiatanResponse"
                    }
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "urusans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.RenjaUrusanResponse"
                    }
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.RenjaProgramResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorRenjaResponse"
                    }
                },
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_program": {
                    "type": "string",
                    "example": "1.01.01.01"
                },
                "pagu_anggaran": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PaguAnggaranRenjaResponse"
                    }
                },
                "program": {
                    "type": "string",
                    "example": "PROGRAM X"
                }
            }
        },
        "web.RenjaSubkegiatanResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorRenjaResponse"
                    }
                },
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_subkegiatan": {
                    "type": "string",
                    "example": "1.01.01.01.01.01.0001"
                },
                "pagu_anggaran": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PaguAnggaranRenjaResponse"
                    }
                },
                "subkegiatan": {
                    "type": "string",
                    "example": "SUBKEGIATAN X"
                }
            }
        },
        "web.RenjaUrusanResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_urusan": {
                    "type": "string",
                    "example": "1"
                },
                "pagu_anggaran": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PaguAnggaranRenjaResponse"
                    }
                },
                "urusan": {
                    "type": "string",
                    "example": "URUSAN PENUNJANG"
                }
            }
        },
        "web.SasaranOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorSasaranPenetapanResponse"
                    }
                },
                "kode_sasaran_opd": {
                    "type": "string",
                    "example": "SAS-001"
                },
                "kode_tujuan_opd": {
                    "type": "string",
                    "example": "TUJ-OPD-123"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2029"
                },
                "sasaran_opd": {
                    "type": "string",
                    "example": "Meningkatnya Nilai SAKIP"
                }
            }
        },
        "web.SasaranPemdaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorPemdaPenetapanResponse"
                    }
                },
                "kode_sasaran_pemda": {
                    "type": "string",
                    "example": "SAS-PEM-1"
                },
                "kode_tujuan_pemda": {
                    "type": "string",
                    "example": "TUJ-PEM-1"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2030"
                },
                "sasaran_pemda": {
                    "type": "string",
                    "example": "SASARAN PENUNJANG"
                }
            }
        },
        "web.SasaranPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.02.0.00.0.00.01.0000"
                },
                "sasaran_opds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.SasaranOpdResponse"
                    }
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.SasaranPenetapanPemdaResponse": {
            "type": "object",
            "properties": {
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "sasaran_pemdas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.SasaranPemdaResponse"
                    }
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.SyncPenetapanOpdRequest": {
            "type": "object",
            "properties": {
                "kode_opd": {
                    "type": "string",
                    "example": "1.22.33"
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "web.SyncPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "jenis_penetapan": {
                    "type": "string",
                    "example": "TUJUAN-OPD"
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.22.33"
                },
                "processed_at": {
                    "type": "string"
                },
                "processed_summary": {
                    "$ref": "#/definitions/web.SyncPenetapanOpdSummary"
                },
                "status": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "sync_id": {
                    "type": "integer",
                    "example": 155
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                }
            }
        },
        "web.SyncPenetapanOpdSummary": {
            "type": "object",
            "properties": {
                "indikator": {
                    "type": "integer",
                    "example": 3
                },
                "renja": {
                    "type": "integer",
                    "example": 1
                },
                "sasaran": {
                    "type": "integer",
                    "example": 1
                },
                "target": {
                    "type": "integer",
                    "example": 4
                },
                "tujuan": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.TargetIndikatorResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "kode_target": {
                    "type": "string",
                    "example": "TGT-IND-01"
                },
                "satuan": {
                    "type": "string",
                    "example": "%"
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                },
                "target": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "web.TargetPemdaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_target": {
                    "type": "string"
                },
                "satuan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                },
                "target": {
                    "type": "number"
                }
            }
        },
        "web.TargetPkResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "kode_target_pk": {
                    "type": "string",
                    "example": "TGT-001"
                },
                "kode_target_sasaran_opd": {
                    "type": "string",
                    "example": "TGT-1"
                },
                "satuan": {
                    "type": "string",
                    "example": "persen"
                },
                "tahun": {
                    "type": "integer",
                    "example": 2025
                },
                "target": {
                    "type": "number",
                    "example": 95
                }
            }
        },
        "web.TargetRenja": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "kode_target": {
                    "type": "string",
                    "example": "TRG-RENJA-123"
                },
                "satuan": {
                    "type": "string",
                    "example": "%"
                },
                "tahun": {
                    "type": "integer",
                    "example": 2026
                },
                "target": {
                    "type": "number",
                    "example": 12
                }
            }
        },
        "web.TujuanOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorTujuanPenetapanResponse"
                    }
                },
                "kode_tujuan_opd": {
                    "type": "string",
                    "example": "TUJ-001"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2029"
                },
                "tujuan_opd": {
                    "type": "string",
                    "example": "Meningkatkan kualitas pelayanan publik"
                }
            }
        },
        "web.TujuanPemdaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorPemdaPenetapanResponse"
                    }
                },
                "kode_tujuan_pemda": {
                    "type": "string",
                    "example": "TUJ-PEM-1"
                },
                "misi": {
                    "type": "string",
                    "example": "Misi Kota 1"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2030"
                },
                "tujuan_pemda": {
                    "type": "string",
                    "example": "Tujuan Pemda 1"
                },
                "visi": {
                    "type": "string",
                    "example": "Terpenuhinya ..."
                }
            }
        },
        "web.TujuanPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.02.0.00.0.00.01.0000"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "tujuan_opds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TujuanOpdResponse"
                    }
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.TujuanPenetapanPemdaResponse": {
            "type": "object",
            "properties": {
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "tujuan_pemdas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TujuanPemdaResponse"
                    }
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.TujuanSasaranOpdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorTujuanPenetapanResponse"
                    }
                },
                "kode_tujuan_opd": {
                    "type": "string",
                    "example": "TUJ-001"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2029"
                },
                "sasaran_opds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.SasaranOpdResponse"
                    }
                },
                "tujuan_opd": {
                    "type": "string",
                    "example": "Meningkatkan kualitas pelayanan publik"
                }
            }
        },
        "web.TujuanSasaranPenetapanOpdResponse": {
            "type": "object",
            "properties": {
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "kode_opd": {
                    "type": "string",
                    "example": "1.02.0.00.0.00.01.0000"
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "tujuan_opds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TujuanSasaranOpdResponse"
                    }
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.TujuanSasaranPenetapanPemdaResponse": {
            "type": "object",
            "properties": {
                "is_locked": {
                    "type": "boolean",
                    "example": true
                },
                "tahun_aktif": {
                    "type": "integer",
                    "example": 2025
                },
                "tujuan_pemdas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.TujuanWithSasaranPemdaResponse"
                    }
                },
                "versi": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "web.TujuanWithSasaranPemdaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "indikators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.IndikatorPemdaPenetapanResponse"
                    }
                },
                "kode_tujuan_pemda": {
                    "type": "string",
                    "example": "TUJ-PEM-1"
                },
                "misi": {
                    "type": "string",
                    "example": "Misi Kota 1"
                },
                "periode": {
                    "type": "string",
                    "example": "2025-2030"
                },
                "sasaran_pemdas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.SasaranPemdaResponse"
                    }
                },
                "tujuan_pemda": {
                    "type": "string",
                    "example": "Tujuan Pemda 1"
                },
                "visi": {
                    "type": "string",
                    "example": "Terpenuhinya ..."
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Penetapan Service",
	Description:      "Service snapshot penetapan tujuan, sasaran, renja, rekin untuk pemda, opd, dan individu",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
